import type { Metadata } from "next";
import PontoHeader from "./components/header";
import PontoFooter from "./components/footer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Residuum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Toaster richColors />
      <PontoHeader />
      <div className="flex grid h-screen justify-items-center">
        <div className="">{children}</div>
      </div>
      <PontoFooter />
    </>
  );
}
