import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import PontoHeader from "./components/header";
import PontoFooter from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
      <PontoHeader/>
        <div className="flex h-screen grid justify-items-center">
      <div className="">
          {children}
        </div>
        </div>
        <PontoFooter/>
        </>
  );
}
